# Generated by Django 4.2.2 on 2023-06-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Awesome_Cart', '0002_rename_products_details_products_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Detail',
            new_name='Product',
        ),
    ]
