# Generated by Django 4.2.2 on 2023-06-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Description', models.CharField(max_length=500)),
                ('Product_Price', models.IntegerField()),
                ('Product_Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
