# Generated by Django 4.2.2 on 2023-06-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Awesome_Cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Details',
            new_name='Products_Detail',
        ),
    ]
